In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# BUILT IN METHODS

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ZEROS AND ONES

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.zeros((2,3))-np.ones((2,3))

array([[-1., -1., -1.],
       [-1., -1., -1.]])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

np.eye(5)+np.ones((5,5))

# RANDOM

In [24]:
np.random.rand(2)

array([0.68302909, 0.06667775])

In [26]:
np.random.rand(5,5)

array([[0.25611772, 0.69041865, 0.0642576 , 0.43105453, 0.75540663],
       [0.18502158, 0.41151164, 0.43989094, 0.93036029, 0.93069742],
       [0.52569352, 0.79580455, 0.27430396, 0.4220502 , 0.68318442],
       [0.86959955, 0.04814526, 0.55239318, 0.92464022, 0.72919373],
       [0.9152093 , 0.97414615, 0.4892065 , 0.12346615, 0.01370969]])

In [37]:
arr = np.arange(13)
ranarr = np.random.randint(0,5,10)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
ranarr.max()

4

In [41]:
ranarr.max()

4

In [42]:
arr = np.arange(13)
ranarr = np.random.randint(0,5,10)

In [43]:
ranarr

array([1, 1, 3, 2, 1, 0, 3, 0, 4, 1])

In [44]:
import numpy as np

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [60]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [58]:
import numpy as np

In [59]:
np.ones(4)

array([1., 1., 1., 1.])